'use strict';
const $=s=>document.querySelector(s);
const templates={sprint:'Run a 10-minute sprint: ask three questions, one at a time.',sba:'Give me five formative single best answer questions, one at a time. Hide the correct answer until I commit, then explain each option.',osce:'Run a mock OSCE or viva. Give only the candidate task first. Wait until I say done before feedback. Do not infer hands-on competence from my description.'};
function generate(){const topic=$('#topic').value.trim()||'Hip fractures';const mode=$('input[name=mode]:checked').value;$('#prompt').value=`I am a medical student revising orthopaedic finals. My topic is: ${topic}. ${templates[mode]} Wait for my answer and reasoning before giving formative feedback. Focus on ${$('#focus').value.toLowerCase()}. Revisit my weakest area with a fresh question and finish with a short recap. Flag uncertainty and do not invent references. This is educational practice, not patient-care advice.`;$('#status').textContent='Starter updated. Inspect and edit it before copying.';$('#open-chat').classList.remove('copied');}
$('#topic').addEventListener('input',generate);document.querySelectorAll('[name=mode]').forEach(el=>el.addEventListener('change',generate));$('#focus').addEventListener('change',generate);generate();$('#copy-starter').disabled=false;
$('#copy-starter').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#prompt').value);$('#status').textContent='Prompt copied. Paste your prompt into the chat to begin.';$('#open-chat').classList.add('copied');}catch{ $('#editor').open=true;$('#prompt').focus();$('#prompt').select();$('#status').textContent='Clipboard unavailable. Your prompt is selected: copy it manually, then open OrthoSG and paste it into the chat.';}});
document.querySelectorAll('.use-example').forEach(button=>{button.disabled=false;button.addEventListener('click',()=>{$('#prompt').value=button.closest('details').querySelector('.example-text').textContent.trim();$('#editor').open=true;$('#prompt').focus();$('#status').textContent='Example loaded. Edit or copy this prompt. Changing the topic, format or settings replaces it with a generated starter.';$('#open-chat').classList.remove('copied');});});
$('#prompt').addEventListener('input',()=>{$('#open-chat').classList.remove('copied');$('#status').textContent='Prompt edited. Copy it when ready. Changing topic, format or settings regenerates the starter.';});
const stages=[['QUESTION','?','Start with one question.','“Which part of this topic would you like to explain?”'],['YOUR REASONING','…','Make your thinking visible.','“Here is my explanation, and the part I am unsure about.”'],['FEEDBACK','↗','Find what to revisit.','Ask for a reasoning gap, then check the explanation and its sources.'],['FRESH QUESTION','↻','Try the idea again.','Request a different question to revisit the same concept.']];
const motion=matchMedia('(prefers-reduced-motion: reduce)');let paused=motion.matches;
function reset(){ $('#cycle-object').style.removeProperty('--rx');$('#cycle-object').style.removeProperty('--ry');}
function setMotion(){reset();$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').textContent=paused?'Enable 3D motion':'Pause 3D motion';}
$('#motion').addEventListener('click',()=>{paused=!paused;setMotion()});motion.addEventListener('change',()=>{paused=motion.matches;setMotion()});setMotion();
document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.step),s=stages[i];document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('#step-number').textContent=`0${i+1} / ${s[0]}`;$('.cycle-symbol').textContent=s[1];$('#demo-title').textContent=s[2];$('#demo-copy').textContent=s[3];$('#demo-status').textContent=`Step ${i+1}: ${s[2]} ${s[3]}`;if(!paused&&!motion.matches){$('#cycle-object').style.setProperty('--ry',`${[-14,10,-8,14][i]}deg`);}}));
$('.perspective').addEventListener('pointermove',e=>{if(paused||motion.matches||e.pointerType!=='mouse')return;const r=e.currentTarget.getBoundingClientRect();$('#cycle-object').style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*24}deg`);$('#cycle-object').style.setProperty('--rx',`${(.5-(e.clientY-r.top)/r.height)*16}deg`);});$('.perspective').addEventListener('pointerleave',reset);
